version: 2
updates:

  - package-ecosystem: github-actions
    directories:
      - /
    schedule:
      interval: weekly

  - package-ecosystem: docker
    directories:
      - '*'
    schedule:
      interval: weekly
