apiVersion: v1
kind: Service
metadata:
  name: demo-api-service
spec:
  selector:
    app: demo-api
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443

    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
